import{A as l,a as u,i as p,S as d}from"./assets/vendor-11987e08.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const f=new l(".about-list",{duration:400,showMultiple:!0,beforeOpen:r=>{const t=r.querySelector(".about-btn-icon");t.style.transition="transform 0.5s",t.style.transform="rotate(180deg)"},beforeClose:r=>{const t=r.querySelector(".about-btn-icon");t.style.transition="transform 0.5s",t.style.transform="rotate(0deg)"}});f.open(0);document.addEventListener("DOMContentLoaded",w);function w(){new l(".faq-column",{duration:500,showMultiple:!0,beforeOpen:r=>{const t=r.querySelector(".faq-arrow-img");t.style.transition="transform 0.5s",t.style.transform="rotate(180deg)"},beforeClose:r=>{const t=r.querySelector(".faq-arrow-img");t.style.transition="transform 0.5s",t.style.transform="rotate(0deg)"}})}const m="https://portfolio-js.b.goit.study/api",y="/reviews";async function v(){const{data:r}=await u.get(`${m}${y}`);return r}function g(r,t){const i=r.map(({_id:n,author:e,avatar_url:o,review:s})=>`
      <li class="reviews-item swiper-slide" id="${n}">
        <img class="reviews-item-img" src="${o}" alt="${e}" width="48" height="48" />
        <h3 class="reviews-item-title">${e}</h3>
        <p class="reviews-item-discription">
          ${s}
        </p>
      </li>
    `).join("");t.insertAdjacentHTML("beforeend",i)}const a=document.querySelector(".reviews-list"),h=document.querySelector(".reviews-error"),c=document.querySelector(".reviews-btn-wrapper");b();async function b(){try{const r=await v();g(r,a),c.classList.remove("hidden")}catch{a.classList.add("hidden"),reviewsSwiper.classList.add("hidden"),c.classList.add("hidden"),h.classList.remove("hidden"),p.show({message:"Sorry, something went wrong. The reviews are not available",messageColor:"#fafafb",messageSize:"16px",position:"topRight",backgroundColor:"#ef4040"})}}function S(){document.querySelectorAll(".covers-content").forEach(t=>{const i=t.querySelectorAll(".covers-marquee-line"),n=t.getBoundingClientRect(),e=window.innerHeight,o=Math.min(n.bottom,e)-Math.max(n.top,0);i.forEach(s=>{o/e>=.2?s.style.animationPlayState="running":s.style.animationPlayState="paused"})})}window.addEventListener("scroll",S);const L=document.querySelector(".project-swiper"),q={navigation:{nextEl:".project-btn-next",prevEl:".project-btn-prev"},keyboard:{enabled:!0,onlyInViewport:!1}};new d(L,q);const E=document.querySelector(".reviews-swiper"),P={navigation:{nextEl:".reviews-btn-next",prevEl:".reviews-btn-prev"},keyboard:{enabled:!0,onlyInViewport:!1},breakpoints:{320:{slidesPerView:1},768:{slidesPerView:2,spaceBetween:16},1280:{slidesPerView:4,spaceBetween:16}}};new d(E,P);
//# sourceMappingURL=commonHelpers.js.map
