import './js/about-accordion.js';
import './js/faq.js';
import './js/cuting-input-value.js';
import './js/post-request.js';
import './js/reviews-fuctions.js';
import './js/covers.js';
import './js/header-modal-window.js';
import './js/swiper.js';
import './js/modal.js';
